name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 0.7.1
author: zmtzawqlp <zmtzawqlp@live.com>
homepage: https://github.com/fluttercandies/extended_image

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image_library: any
  # extended_image_library:
  #   git:
  #       url: https://github.com/fluttercandies/extended_image_library.git


flutter:
